Repository LectureGoggles/FlaskAPI, pull requests merged in 2020-01, with the labels that each got.

#95 Add Docker support
  .dockerignore
  .gitignore
  .vscode/settings.json
  Dockerfile
  conf/uwsgi.ini
Labels: enhancement

#96 Add Docker support
  .dockerignore
  .gitignore
  .vscode/settings.json
  Dockerfile
  conf/uwsgi.ini
Labels: enhancement

#97 Azure pipelines
  azure-pipelines.yml
Labels: enhancement

#98 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: enhancement

#99 Update Dockerfile
  Dockerfile
Labels: bug

#100 Add psycopg2 protocol and remove environment variables from build
  Dockerfile
  app/__init__.py
Labels: bug

#101 Support pipenv
  .envrc
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  launchinstructions.txt
  requirements.txt
Labels: enhancement

#102 Add new Docker image tags and Support pipenv
  .envrc
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  azure-pipelines.yml
  launchinstructions.txt
  requirements.txt
Labels: enhancement

#104 Upgrade to Python 3.7
  Dockerfile
  Pipfile
Labels: dependencies
